name: ChestLocker
version: 1.0.0
main: benj.chestlocker.ChestLockerPlugin
api-version: 1.20
authors: [ Benj4368 ]
description: Permet le verrouillage et la gestion des droits d'accès aux conteneurs.
commands:
  chestlocker:
    description: Commande principale pour le plugin ChestLocker.
    usage: /chestlocker <lock | unlock | add | remove | check>

permissions:
  chestlocker.admin:
    description: Permission admin du plugin ChestLocker.
    default: op
  chestlocker.user:
    description: Permission basique du plugin ChestLocker.
    default: true