name: ChatMentioner
version: 1.0.0
main: benj.chatmentioner.ChatMentionerPlugin
api-version: 1.20
authors: [ Benj4368 ]
description: Joue un son de notification lorsqu'un joueur est mentionné dans le chat.
commands:
  chatmentioner:
    description: Activer ou désactiver les notifications de mention dans le chat.
    usage: /chatmentioner <on | off>

permissions:
  chatmentioner.admin:
    description: Permission admin du plugin ChatMentioner.
    default: op